//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("HitsModel", "FK_Requests_RequestThemes", "RequestThemes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Hit.Models.RequestThemes), "Requests", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Hit.Models.Requests), true)]
[assembly: EdmRelationshipAttribute("HitsModel", "FK_Requests_RequestTypes", "RequestTypes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Hit.Models.RequestTypes), "Requests", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Hit.Models.Requests), true)]

#endregion

namespace Hit.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class HitsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new HitsEntities object using the connection string found in the 'HitsEntities' section of the application configuration file.
        /// </summary>
        public HitsEntities() : base("name=HitsEntities", "HitsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HitsEntities object.
        /// </summary>
        public HitsEntities(string connectionString) : base(connectionString, "HitsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HitsEntities object.
        /// </summary>
        public HitsEntities(EntityConnection connection) : base(connection, "HitsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Requests> Requests
        {
            get
            {
                if ((_Requests == null))
                {
                    _Requests = base.CreateObjectSet<Requests>("Requests");
                }
                return _Requests;
            }
        }
        private ObjectSet<Requests> _Requests;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RequestThemes> RequestThemes
        {
            get
            {
                if ((_RequestThemes == null))
                {
                    _RequestThemes = base.CreateObjectSet<RequestThemes>("RequestThemes");
                }
                return _RequestThemes;
            }
        }
        private ObjectSet<RequestThemes> _RequestThemes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RequestTypes> RequestTypes
        {
            get
            {
                if ((_RequestTypes == null))
                {
                    _RequestTypes = base.CreateObjectSet<RequestTypes>("RequestTypes");
                }
                return _RequestTypes;
            }
        }
        private ObjectSet<RequestTypes> _RequestTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Requests EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRequests(Requests requests)
        {
            base.AddObject("Requests", requests);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RequestThemes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRequestThemes(RequestThemes requestThemes)
        {
            base.AddObject("RequestThemes", requestThemes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RequestTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRequestTypes(RequestTypes requestTypes)
        {
            base.AddObject("RequestTypes", requestTypes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HitsModel", Name="Requests")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Requests : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Requests object.
        /// </summary>
        /// <param name="requestId">Initial value of the RequestId property.</param>
        public static Requests CreateRequests(global::System.Int32 requestId)
        {
            Requests requests = new Requests();
            requests.RequestId = requestId;
            return requests;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RequestId
        {
            get
            {
                return _RequestId;
            }
            set
            {
                if (_RequestId != value)
                {
                    OnRequestIdChanging(value);
                    ReportPropertyChanging("RequestId");
                    _RequestId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RequestId");
                    OnRequestIdChanged();
                }
            }
        }
        private global::System.Int32 _RequestId;
        partial void OnRequestIdChanging(global::System.Int32 value);
        partial void OnRequestIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RequestTypeId
        {
            get
            {
                return _RequestTypeId;
            }
            set
            {
                OnRequestTypeIdChanging(value);
                ReportPropertyChanging("RequestTypeId");
                _RequestTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RequestTypeId");
                OnRequestTypeIdChanged();
            }
        }
        private Nullable<global::System.Int32> _RequestTypeId;
        partial void OnRequestTypeIdChanging(Nullable<global::System.Int32> value);
        partial void OnRequestTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RequestThemeId
        {
            get
            {
                return _RequestThemeId;
            }
            set
            {
                OnRequestThemeIdChanging(value);
                ReportPropertyChanging("RequestThemeId");
                _RequestThemeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RequestThemeId");
                OnRequestThemeIdChanged();
            }
        }
        private Nullable<global::System.Int32> _RequestThemeId;
        partial void OnRequestThemeIdChanging(Nullable<global::System.Int32> value);
        partial void OnRequestThemeIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HitsModel", "FK_Requests_RequestThemes", "RequestThemes")]
        public RequestThemes RequestThemes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RequestThemes>("HitsModel.FK_Requests_RequestThemes", "RequestThemes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RequestThemes>("HitsModel.FK_Requests_RequestThemes", "RequestThemes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<RequestThemes> RequestThemesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RequestThemes>("HitsModel.FK_Requests_RequestThemes", "RequestThemes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<RequestThemes>("HitsModel.FK_Requests_RequestThemes", "RequestThemes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HitsModel", "FK_Requests_RequestTypes", "RequestTypes")]
        public RequestTypes RequestTypes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RequestTypes>("HitsModel.FK_Requests_RequestTypes", "RequestTypes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RequestTypes>("HitsModel.FK_Requests_RequestTypes", "RequestTypes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<RequestTypes> RequestTypesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RequestTypes>("HitsModel.FK_Requests_RequestTypes", "RequestTypes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<RequestTypes>("HitsModel.FK_Requests_RequestTypes", "RequestTypes", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HitsModel", Name="RequestThemes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RequestThemes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RequestThemes object.
        /// </summary>
        /// <param name="requestThemeId">Initial value of the RequestThemeId property.</param>
        /// <param name="requestTheme">Initial value of the RequestTheme property.</param>
        public static RequestThemes CreateRequestThemes(global::System.Int32 requestThemeId, global::System.String requestTheme)
        {
            RequestThemes requestThemes = new RequestThemes();
            requestThemes.RequestThemeId = requestThemeId;
            requestThemes.RequestTheme = requestTheme;
            return requestThemes;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RequestThemeId
        {
            get
            {
                return _RequestThemeId;
            }
            set
            {
                if (_RequestThemeId != value)
                {
                    OnRequestThemeIdChanging(value);
                    ReportPropertyChanging("RequestThemeId");
                    _RequestThemeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RequestThemeId");
                    OnRequestThemeIdChanged();
                }
            }
        }
        private global::System.Int32 _RequestThemeId;
        partial void OnRequestThemeIdChanging(global::System.Int32 value);
        partial void OnRequestThemeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RequestTheme
        {
            get
            {
                return _RequestTheme;
            }
            set
            {
                OnRequestThemeChanging(value);
                ReportPropertyChanging("RequestTheme");
                _RequestTheme = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RequestTheme");
                OnRequestThemeChanged();
            }
        }
        private global::System.String _RequestTheme;
        partial void OnRequestThemeChanging(global::System.String value);
        partial void OnRequestThemeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HitsModel", "FK_Requests_RequestThemes", "Requests")]
        public EntityCollection<Requests> Requests
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Requests>("HitsModel.FK_Requests_RequestThemes", "Requests");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Requests>("HitsModel.FK_Requests_RequestThemes", "Requests", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HitsModel", Name="RequestTypes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RequestTypes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RequestTypes object.
        /// </summary>
        /// <param name="requestTypeId">Initial value of the RequestTypeId property.</param>
        /// <param name="requestType">Initial value of the RequestType property.</param>
        public static RequestTypes CreateRequestTypes(global::System.Int32 requestTypeId, global::System.String requestType)
        {
            RequestTypes requestTypes = new RequestTypes();
            requestTypes.RequestTypeId = requestTypeId;
            requestTypes.RequestType = requestType;
            return requestTypes;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RequestTypeId
        {
            get
            {
                return _RequestTypeId;
            }
            set
            {
                if (_RequestTypeId != value)
                {
                    OnRequestTypeIdChanging(value);
                    ReportPropertyChanging("RequestTypeId");
                    _RequestTypeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RequestTypeId");
                    OnRequestTypeIdChanged();
                }
            }
        }
        private global::System.Int32 _RequestTypeId;
        partial void OnRequestTypeIdChanging(global::System.Int32 value);
        partial void OnRequestTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RequestType
        {
            get
            {
                return _RequestType;
            }
            set
            {
                OnRequestTypeChanging(value);
                ReportPropertyChanging("RequestType");
                _RequestType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RequestType");
                OnRequestTypeChanged();
            }
        }
        private global::System.String _RequestType;
        partial void OnRequestTypeChanging(global::System.String value);
        partial void OnRequestTypeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HitsModel", "FK_Requests_RequestTypes", "Requests")]
        public EntityCollection<Requests> Requests
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Requests>("HitsModel.FK_Requests_RequestTypes", "Requests");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Requests>("HitsModel.FK_Requests_RequestTypes", "Requests", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HitsModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }

    #endregion
    
}
