//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("HitsModel", "FK_Requests_RequestThemes", "RequestThemes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Hit.Models.RequestThemes), "Requests", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Hit.Models.Requests), true)]
[assembly: EdmRelationshipAttribute("HitsModel", "FK_Requests_RequestTypes", "RequestTypes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Hit.Models.RequestTypes), "Requests", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Hit.Models.Requests), true)]

#endregion

namespace Hit.Models
{
    #region Contexts

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class HitsEntities : ObjectContext
    {
        #region Constructors

        /// <summary>
        /// Initializes a new HitsEntities object using the connection string found in the 'HitsEntities' section of the application configuration file.
        /// </summary>
        public HitsEntities()
            : base("name=HitsEntities", "HitsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        /// <summary>
        /// Initialize a new HitsEntities object.
        /// </summary>
        public HitsEntities(string connectionString)
            : base(connectionString, "HitsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        /// <summary>
        /// Initialize a new HitsEntities object.
        /// </summary>
        public HitsEntities(EntityConnection connection)
            : base(connection, "HitsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        #endregion

        #region Partial Methods

        partial void OnContextCreated();

        #endregion

        #region ObjectSet Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Requests> Requests
        {
            get
            {
                if ((_Requests == null))
                {
                    _Requests = base.CreateObjectSet<Requests>("Requests");
                }
                return _Requests;
            }
        }
        private ObjectSet<Requests> _Requests;

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RequestThemes> RequestThemes
        {
            get
            {
                if ((_RequestThemes == null))
                {
                    _RequestThemes = base.CreateObjectSet<RequestThemes>("RequestThemes");
                }
                return _RequestThemes;
            }
        }
        private ObjectSet<RequestThemes> _RequestThemes;

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RequestTypes> RequestTypes
        {
            get
            {
                if ((_RequestTypes == null))
                {
                    _RequestTypes = base.CreateObjectSet<RequestTypes>("RequestTypes");
                }
                return _RequestTypes;
            }
        }
        private ObjectSet<RequestTypes> _RequestTypes;

        #endregion
        #region AddTo Methods

        /// <summary>
        /// Deprecated Method for adding a new object to the Requests EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRequests(Requests requests)
        {
            base.AddObject("Requests", requests);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the RequestThemes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRequestThemes(RequestThemes requestThemes)
        {
            base.AddObject("RequestThemes", requestThemes);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the RequestTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRequestTypes(RequestTypes requestTypes)
        {
            base.AddObject("RequestTypes", requestTypes);
        }

        #endregion
    }


    #endregion

    #region Entities

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName = "HitsModel", Name = "Requests")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]
    public partial class Requests : EntityObject
    {
        #region Factory Method

        /// <summary>
        /// Create a new Requests object.
        /// </summary>
        /// <param name="requestId">Initial value of the RequestId property.</param>
        /// <param name="requestTypeId">Initial value of the RequestTypeId property.</param>
        /// <param name="requestThemeId">Initial value of the RequestThemeId property.</param>
        /// <param name="requestDate">Initial value of the RequestDate property.</param>
        public static Requests CreateRequests(global::System.Int32 requestId, global::System.Int32 requestTypeId, global::System.Int32 requestThemeId, global::System.DateTime requestDate)
        {
            Requests requests = new Requests();
            requests.RequestId = requestId;
            requests.RequestTypeId = requestTypeId;
            requests.RequestThemeId = requestThemeId;
            requests.RequestDate = requestDate;
            return requests;
        }

        #endregion
        #region Primitive Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = true, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Int32 RequestId
        {
            get
            {
                return _RequestId;
            }
            set
            {
                if (_RequestId != value)
                {
                    OnRequestIdChanging(value);
                    ReportPropertyChanging("RequestId");
                    _RequestId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RequestId");
                    OnRequestIdChanged();
                }
            }
        }
        private global::System.Int32 _RequestId;
        partial void OnRequestIdChanging(global::System.Int32 value);
        partial void OnRequestIdChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Int32 RequestTypeId
        {
            get
            {
                return _RequestTypeId;
            }
            set
            {
                OnRequestTypeIdChanging(value);
                ReportPropertyChanging("RequestTypeId");
                _RequestTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RequestTypeId");
                OnRequestTypeIdChanged();
            }
        }
        private global::System.Int32 _RequestTypeId;
        partial void OnRequestTypeIdChanging(global::System.Int32 value);
        partial void OnRequestTypeIdChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Int32 RequestThemeId
        {
            get
            {
                return _RequestThemeId;
            }
            set
            {
                OnRequestThemeIdChanging(value);
                ReportPropertyChanging("RequestThemeId");
                _RequestThemeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RequestThemeId");
                OnRequestThemeIdChanged();
            }
        }
        private global::System.Int32 _RequestThemeId;
        partial void OnRequestThemeIdChanging(global::System.Int32 value);
        partial void OnRequestThemeIdChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.DateTime RequestDate
        {
            get
            {
                return _RequestDate;
            }
            set
            {
                OnRequestDateChanging(value);
                ReportPropertyChanging("RequestDate");
                _RequestDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RequestDate");
                OnRequestDateChanged();
            }
        }
        private global::System.DateTime _RequestDate;
        partial void OnRequestDateChanging(global::System.DateTime value);
        partial void OnRequestDateChanged();

        #endregion

        #region Navigation Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HitsModel", "FK_Requests_RequestThemes", "RequestThemes")]
        public RequestThemes RequestThemes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RequestThemes>("HitsModel.FK_Requests_RequestThemes", "RequestThemes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RequestThemes>("HitsModel.FK_Requests_RequestThemes", "RequestThemes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<RequestThemes> RequestThemesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RequestThemes>("HitsModel.FK_Requests_RequestThemes", "RequestThemes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<RequestThemes>("HitsModel.FK_Requests_RequestThemes", "RequestThemes", value);
                }
            }
        }

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HitsModel", "FK_Requests_RequestTypes", "RequestTypes")]
        public RequestTypes RequestTypes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RequestTypes>("HitsModel.FK_Requests_RequestTypes", "RequestTypes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RequestTypes>("HitsModel.FK_Requests_RequestTypes", "RequestTypes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<RequestTypes> RequestTypesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RequestTypes>("HitsModel.FK_Requests_RequestTypes", "RequestTypes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<RequestTypes>("HitsModel.FK_Requests_RequestTypes", "RequestTypes", value);
                }
            }
        }

        #endregion
    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName = "HitsModel", Name = "RequestThemes")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]
    public partial class RequestThemes : EntityObject
    {
        #region Factory Method

        /// <summary>
        /// Create a new RequestThemes object.
        /// </summary>
        /// <param name="requestThemeId">Initial value of the RequestThemeId property.</param>
        /// <param name="requestTheme">Initial value of the RequestTheme property.</param>
        public static RequestThemes CreateRequestThemes(global::System.Int32 requestThemeId, global::System.String requestTheme)
        {
            RequestThemes requestThemes = new RequestThemes();
            requestThemes.RequestThemeId = requestThemeId;
            requestThemes.RequestTheme = requestTheme;
            return requestThemes;
        }

        #endregion
        #region Primitive Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = true, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Int32 RequestThemeId
        {
            get
            {
                return _RequestThemeId;
            }
            set
            {
                if (_RequestThemeId != value)
                {
                    OnRequestThemeIdChanging(value);
                    ReportPropertyChanging("RequestThemeId");
                    _RequestThemeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RequestThemeId");
                    OnRequestThemeIdChanged();
                }
            }
        }
        private global::System.Int32 _RequestThemeId;
        partial void OnRequestThemeIdChanging(global::System.Int32 value);
        partial void OnRequestThemeIdChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.String RequestTheme
        {
            get
            {
                return _RequestTheme;
            }
            set
            {
                OnRequestThemeChanging(value);
                ReportPropertyChanging("RequestTheme");
                _RequestTheme = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RequestTheme");
                OnRequestThemeChanged();
            }
        }
        private global::System.String _RequestTheme;
        partial void OnRequestThemeChanging(global::System.String value);
        partial void OnRequestThemeChanged();

        #endregion

        #region Navigation Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HitsModel", "FK_Requests_RequestThemes", "Requests")]
        public EntityCollection<Requests> Requests
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Requests>("HitsModel.FK_Requests_RequestThemes", "Requests");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Requests>("HitsModel.FK_Requests_RequestThemes", "Requests", value);
                }
            }
        }

        #endregion
    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName = "HitsModel", Name = "RequestTypes")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]
    public partial class RequestTypes : EntityObject
    {
        #region Factory Method

        /// <summary>
        /// Create a new RequestTypes object.
        /// </summary>
        /// <param name="requestTypeId">Initial value of the RequestTypeId property.</param>
        /// <param name="requestType">Initial value of the RequestType property.</param>
        public static RequestTypes CreateRequestTypes(global::System.Int32 requestTypeId, global::System.String requestType)
        {
            RequestTypes requestTypes = new RequestTypes();
            requestTypes.RequestTypeId = requestTypeId;
            requestTypes.RequestType = requestType;
            return requestTypes;
        }

        #endregion
        #region Primitive Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = true, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Int32 RequestTypeId
        {
            get
            {
                return _RequestTypeId;
            }
            set
            {
                if (_RequestTypeId != value)
                {
                    OnRequestTypeIdChanging(value);
                    ReportPropertyChanging("RequestTypeId");
                    _RequestTypeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RequestTypeId");
                    OnRequestTypeIdChanged();
                }
            }
        }
        private global::System.Int32 _RequestTypeId;
        partial void OnRequestTypeIdChanging(global::System.Int32 value);
        partial void OnRequestTypeIdChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.String RequestType
        {
            get
            {
                return _RequestType;
            }
            set
            {
                OnRequestTypeChanging(value);
                ReportPropertyChanging("RequestType");
                _RequestType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RequestType");
                OnRequestTypeChanged();
            }
        }
        private global::System.String _RequestType;
        partial void OnRequestTypeChanging(global::System.String value);
        partial void OnRequestTypeChanged();

        #endregion

        #region Navigation Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HitsModel", "FK_Requests_RequestTypes", "Requests")]
        public EntityCollection<Requests> Requests
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Requests>("HitsModel.FK_Requests_RequestTypes", "Requests");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Requests>("HitsModel.FK_Requests_RequestTypes", "Requests", value);
                }
            }
        }

        #endregion
    }

    #endregion

}
